server:
  port: 8081
spring:
  jpa:
    hibernate:
      ddl-auto: update

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/mercadolivrobd
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 1234
    schema-generate: update
    dialect: POSTGRES
jpa.default.properties.hibernate.hbm2ddl.auto: update
