name: CI/CD - Master

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1 - Clonar o código
      - name: Checkout código
        uses: actions/checkout@v4

      # 2 - Configurar JDK 17
      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3 - Garantir permissão para o gradlew
      - name: Dar permissão de execução ao gradlew
        run: chmod +x gradlew

      # 4 - Build e testes
      - name: Build e Testes
        run: ./gradlew clean build

      # 5 - Deploy versão estável
      - name: Deploy Final
        if: github.ref == 'refs/heads/master'
        run: |
          echo "Deploy versão estável..."
